### ISSUE TITLE
Error running the example experiment

### ISSUE THREAD

**Issue by tingkai-zhang** [sai-prasanna/suggestion-mining-semeval19#6]
Hi, thanks for sharing your work!
I have the following error when trying to run the bert_cnn experiment:
```
2019-11-17 04:43:19,650 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-11-17 04:43:20,015 - INFO - pytorch_transformers.modeling_bert - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-11-17 04:43:20,017 - INFO - pytorch_transformers.modeling_xlnet - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-11-17 04:43:20,269 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-11-17 04:43:20,270 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-11-17 04:43:20,270 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-11-17 04:43:20,270 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
Traceback (most recent call last):
  File "/opt/conda/bin/allennlp", line 10, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/opt/conda/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 101, in main
    import_submodules(package_name)
  File "/opt/conda/lib/python3.6/site-packages/allennlp/common/util.py", line 325, in import_submodules
    path_string = '' if not path else path[0]
TypeError: '_NamespacePath' object does not support indexing
```
OS: Ubuntu 16.04
Install the prerequisite by `pip install -r requirement.txt`

Can you take a look at this issue?

**Comment by sai-prasanna** [comment]
Sure will take a look. I think its related to https://github.com/allenai/allennlp/issues/3103

**Comment by sai-prasanna** [comment]
@tingkai-zhang Were you able to get it working?

Really sorry for the late reply. I have time to look into this now.
